"""added User - Post relationship and post timestamp

Revision ID: 22763df26df9
Revises: b45432c031b2
Create Date: 2020-10-27 02:52:38.021348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22763df26df9'
down_revision = 'b45432c031b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
